# Generated by Django 5.2 on 2026-03-11 18:02

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=users.utils.user_directory_path_gallery)),
                ('comment', models.CharField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('dislikes_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='GalleryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('like', 'Лайк'), ('dislike', 'Дизлайк')], default='like', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Оценка галереи',
                'verbose_name_plural': 'Оценки галереи',
            },
        ),
    ]
