# Generated by Django 5.2 on 2026-03-11 18:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('patronymic', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('-', '-'), ('M', 'Мужской'), ('F', 'Женский')], default='-', max_length=1)),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('city', models.CharField(blank=True, max_length=150)),
                ('hobbies', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('privacy_settings', models.JSONField(blank=True, default=dict, help_text='Словарь настроек приватности, включая список друзей', verbose_name='Настройки приватности')),
                ('birth_year', models.IntegerField(blank=True, choices=[(None, 'Не выбран'), (2008, '2008'), (2007, '2007'), (2006, '2006'), (2005, '2005'), (2004, '2004'), (2003, '2003'), (2002, '2002'), (2001, '2001'), (2000, '2000'), (1999, '1999'), (1998, '1998'), (1997, '1997'), (1996, '1996'), (1995, '1995'), (1994, '1994'), (1993, '1993'), (1992, '1992'), (1991, '1991'), (1990, '1990'), (1989, '1989'), (1988, '1988'), (1987, '1987'), (1986, '1986'), (1985, '1985'), (1984, '1984'), (1983, '1983'), (1982, '1982'), (1981, '1981'), (1980, '1980'), (1979, '1979'), (1978, '1978'), (1977, '1977'), (1976, '1976'), (1975, '1975'), (1974, '1974'), (1973, '1973'), (1972, '1972'), (1971, '1971'), (1970, '1970'), (1969, '1969'), (1968, '1968'), (1967, '1967'), (1966, '1966'), (1965, '1965'), (1964, '1964'), (1963, '1963'), (1962, '1962'), (1961, '1961'), (1960, '1960'), (1959, '1959'), (1958, '1958'), (1957, '1957'), (1956, '1956'), (1955, '1955'), (1954, '1954'), (1953, '1953'), (1952, '1952'), (1951, '1951'), (1950, '1950'), (1949, '1949'), (1948, '1948'), (1947, '1947'), (1946, '1946'), (1945, '1945'), (1944, '1944'), (1943, '1943'), (1942, '1942'), (1941, '1941'), (1940, '1940'), (1939, '1939'), (1938, '1938'), (1937, '1937'), (1936, '1936'), (1935, '1935'), (1934, '1934'), (1933, '1933'), (1932, '1932'), (1931, '1931'), (1930, '1930'), (1929, '1929'), (1928, '1928'), (1927, '1927'), (1926, '1926')], help_text='Год рождения (от 1926 до 2008)', null=True)),
                ('avatar_gallery_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_avatar', to='gallery.gallery', verbose_name='Аватар из галереи')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GalleryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('like', 'Лайк'), ('dislike', 'Дизлайк')], max_length=10, verbose_name='Тип оценки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_ratings', to='gallery.gallery', verbose_name='Галерея')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка галереи',
                'verbose_name_plural': 'Оценки галерей',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'gallery')},
            },
        ),
    ]
